PetBuddy/PetBuddy/Controllers/Pet/PetController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PetBuddy.Controllers.Profile;
using PetBuddy.Models;
using PetBuddy.Services;
using PetBuddy.ViewModels;

namespace PetBuddy.Controllers.Pet
{
    [Authorize]
    public class PetController : Controller
    {
        
        private readonly UserManager<User> userManager;
        private readonly IPetService petService;
        private readonly IImageService imageService;
        private readonly IPlaceService placeService;

        public PetController(UserManager<User> userManager, IPetService petService, 
            IImageService imageService, IPlaceService placeService)
        {
            this.userManager = userManager;
            this.petService = petService;
            this.imageService = imageService;
            this.placeService = placeService;
        }

        [HttpGet("/newpet")]
        public IActionResult NewPet()
        {
            return View(new PetViewModel());
        }

        [HttpPost("/newpet")]
        public async Task<IActionResult> NewPet(PetViewModel newPet)
        {
            if (ModelState.IsValid)
            {
                var currentUser = await userManager.GetUserAsync(HttpContext.User);
                var petId = await petService.AddPetAsync(newPet, currentUser);

                if (newPet.File != null)
                {
                    await imageService.UploadAsync(newPet.File, petId.ToString(), "pet");
                    await petService.SetIndexImageAsync(petId, "pet");
                }

                return RedirectToAction(nameof(ProfileController.MyProfile), "Profile");
            }

            return View(newPet);
        }
        
        [HttpGet("/deletepet/{petId}")]
        public async Task<IActionResult> DeletePet(long petId)
        {
            await petService.DeletePetAsync(petId);
            return RedirectToAction(nameof(ProfileController.MyProfile), "Profile");
        }

        [HttpGet("/editpet/{petId}")]
        public async Task<IActionResult> EditPet(long petId)
        {
            var pet = await petService.FindPetByIdAsync(petId);
            return View(new PetViewModel {PetName = pet.PetName, PetType = pet.PetType, PetDescription = pet.PetDescription});
        }

        [HttpPost("/editpet/{petId}")]
        public async Task<IActionResult> EditPet(PetViewModel editPet, long petId)
        {
            if (ModelState.IsValid)
            {
                await petService.EditPetAsync(editPet, petId);
                if (editPet.File != null)
                {
                    await imageService.UploadAsync(editPet.File, petId.ToString(), "pet");
                    await petService.SetIndexImageAsync(petId, "pet");
                }
                return RedirectToAction(nameof(ProfileController.MyProfile), "Profile");
            }
            
            return View(editPet);
        }
    }
}

PetBuddy/PetBuddy/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width-device-width" />
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <link href="~/css/StyleSheet.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>@ViewBag.Title</title>
</head>
<body>
<div>
    @if (SignInManager.IsSignedIn(User))
    {
        <nav class="navbar sticky-top navbar-light bg-light">
            <div class="container">
            <a class="navbar-brand" asp-action="Home" asp-controller="Home">
                <img src="~/images/logo.png" height="80" width="auto">
            </a>
        <div class="nav-item dropdown">
            <a class="navbar-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="navbar-toggler-icon"></span>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" asp-controller="Home" asp-action="Home">Home page</a>
                <a class="dropdown-item" asp-controller="Profile" asp-action="MyProfile">My profile</a>
                <a class="dropdown-item" asp-controller="Place" asp-action="MyPlace">My place</a>
                <a class="dropdown-item" asp-controller="Profile" asp-action="EditProfile" asp-route-userId="@ViewBag.UserId">Settings</a>
                <a class="dropdown-item" asp-controller="Home" asp-action="Logout">Logout</a>
            </div>
        </div>
        </div>
    </nav>
    }
    <div class="container-body">
            @RenderBody()
        </div>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </div>
</body>
</html>

PetBuddy/PetBuddy/Views/Shared/_PetPartial.cshtml
@model PetViewModel

<form asp-controller="Pet" asp-action="@ViewData["Action"]" method="post" enctype="multipart/form-data">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <div>
                        <h5><label class="card-title" asp-for="PetName"></label></h5>
                        <input class="card-text" type="text" asp-for="PetName" />
                        <span asp-validation-for="PetName" class="text-danger"></span>
                    </div>
                    <div>
                        <h5><label class="card-title" asp-for="PetType"></label></h5>
                        <select class="card-text" type="text" asp-for="PetType">
                            <option value="dog">dog</option>
                            <option value="cat">cat</option>
                            <option value="rabbit">rabbit</option>
                            <option value="snake">snake</option>
                            <option value="ferret">ferret</option>
                        </select>
                    </div>
                    <div>
                        <h5><label class="card-title" asp-for="PetDescription"></label></h5>
                        <textarea class="card-text" asp-for="PetDescription" rows="3" maxlength="200"></textarea>
                        <span asp-validation-for="PetDescription" class="text-danger"></span>
                    </div>
                    <div>
                        <input type="file" asp-for="@Model.File" multiple />
                    </div>
                    <div>
                        <button type="submit" class="btn btn-outline-info">Save</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

PetBuddy/PetBuddy/Views/Shared/_PlacePartial.cshtml
@model PlaceInfoViewModel

    <form asp-controller="Place" asp-action="@ViewData["Action"]" method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="@Model.Price">Price</label>
                    <input type="text" asp-for="@Model.Price" class="form-control">
                    <span asp-validation-for="@Model.Price" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.City">City</label>
                    <input type="text" asp-for="@Model.City" class="form-control">
                    <span asp-validation-for="@Model.City" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.PetType"></label>
                    <input type="text" asp-for="@Model.PetType" placeholder="Dog, cat, rabbit ..." class="form-control">
                    <span asp-validation-for="@Model.PetType" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Description">Description</label>
                    <input type="text" asp-for="@Model.Description" class="form-control">
                    <span asp-validation-for="@Model.Description" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="form-group">
            @if (Model.ErrorMessages != null)
            {
                @foreach (var error in Model.ErrorMessages)
                {
                    <span class="text-danger">@error</span>
                }
            }
            <div>
                <input type="file" asp-for="@Model.File" multiple />
            </div>
            <div>
                <span asp-validation-for="@Model.File" class="text-danger"></span>
            </div>
        </div>
        <button type="submit" class="btn btn-outline-info">@ViewData["Action"]</button>
        @if (@ViewData["Action"].Equals("Add"))
        {
            <a class="btn btn-outline-danger" asp-controller="Home" asp-action="Home" role="button">Cancel</a>
        }
        else
        {
            <a class="btn btn-outline-danger" asp-controller="Place" asp-action="MyPlace" role="button">Cancel</a>
        }
    </form>